name: PDF Cleanup Automation
on:
  schedule:
    - cron: '0 2 * * *'  
  workflow_dispatch:     

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install mssql 

    - name: Run PDF Cleanup
      run: node scripts/cleanup.js 7
      env:
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}