name: PDF Cleanup Automation
on:
  schedule:
    - cron: '0 2 * * *'  
  workflow_dispatch:     

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      DB_SERVER: ${{ secrets.DB_SERVER }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install mssql dotenv


      
    - name: Debug env setup
      run:  |
        echo "Cleanup is starting"
        echo "DB server set? ${DB_SERVER:+Yes}"
        echo "DB name set? ${DB_NAME:+Yes}"
        echo "DB user set? ${DB_USER:+Yes}"
        echo "DB password set? ${DB_PASSWORD:+Yes}"
        echo "DB port set? ${DB_PORT:+Yes}"
      


    - name: Run PDF Cleanup
      run: node scripts/cleanup-converted 7
      working-directory: server
      